
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Principal7 extends javax.swing.JFrame {

    /**
     * Creates new form Principal7
     */
    public Principal7() {
        initComponents();
    }
    ArrayList<Cajero> listaCajeros = new ArrayList();
    ArrayList<Cliente> listaClientes = new ArrayList();
    ArrayList<Producto> listaProductos = new ArrayList();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreCajero = new javax.swing.JTextField();
        jb_crearCajero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_idCajero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombreProducto = new javax.swing.JTextField();
        tf_precioProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jb_crearProducto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_tiempoProcesamiento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_edadCliente = new javax.swing.JTextField();
        jb_crearCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_productos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_cajeros = new javax.swing.JComboBox<>();
        cb_clientes = new javax.swing.JComboBox<>();
        jb_crearOrden = new javax.swing.JButton();
        jb_agregarProducto = new javax.swing.JButton();
        jb_procesarOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel4.setText("Nombre del cajero");

        jb_crearCajero.setText("Crear");
        jb_crearCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearCajeroActionPerformed(evt);
            }
        });

        jLabel5.setText("ID del cajero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jb_crearCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreCajero)
                            .addComponent(tf_idCajero, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_idCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jb_crearCajero)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creacion de Cajeros", jPanel1);

        jLabel6.setText("Nombre del producto");

        jLabel7.setText("Precio");

        jb_crearProducto.setText("Crear");
        jb_crearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearProductoActionPerformed(evt);
            }
        });

        jLabel8.setText("Tiempo de procesamiento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jb_crearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreProducto)
                            .addComponent(tf_precioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(tf_tiempoProcesamiento))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_tiempoProcesamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jb_crearProducto)
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("Creacion de productos", jPanel2);

        jLabel9.setText("Nombre del cliente");

        jLabel10.setText("Edad");

        jb_crearCliente.setText("Crear");
        jb_crearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jb_crearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreCliente)
                            .addComponent(tf_edadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_edadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jb_crearCliente)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creacion de clientes", jPanel4);

        jLabel1.setText("Nombre del cliente");

        cb_productos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>" }));

        jLabel2.setText("Productos");

        jLabel3.setText("Cajero");

        cb_cajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>" }));

        cb_clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>" }));

        jb_crearOrden.setText("Crear orden");
        jb_crearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearOrdenActionPerformed(evt);
            }
        });

        jb_agregarProducto.setText("Agregar producto");
        jb_agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarProductoActionPerformed(evt);
            }
        });

        jb_procesarOrden.setText("Procesar orden");
        jb_procesarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_procesarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_productos, 0, 121, Short.MAX_VALUE)
                            .addComponent(cb_cajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addComponent(jb_agregarProducto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(cb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jb_crearOrden)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_procesarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_crearOrden)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jb_agregarProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_cajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jb_procesarOrden)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearCajeroActionPerformed
        Cajero temp = new Cajero(tf_nombreCajero.getText(),tf_idCajero.getText());
        temp.setVentana(new venta());
        temp.getVentana().getJl_nombreCajero().setText(temp.getNombre());
        temp.getVentana().setVisible(true);
        temp.setHilo(new hilo());
        
        listaCajeros.add(temp);
        tf_nombreCajero.setText("");tf_idCajero.setText("");
    }//GEN-LAST:event_jb_crearCajeroActionPerformed

    private void jb_crearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearProductoActionPerformed
        Producto temp = new Producto(tf_nombreProducto.getText(),tf_precioProducto.getText(),Integer.parseInt(tf_tiempoProcesamiento.getText()));
        listaProductos.add(temp);
        tf_nombreProducto.setText("");tf_precioProducto.setText("");tf_tiempoProcesamiento.setText("");
    }//GEN-LAST:event_jb_crearProductoActionPerformed

    private void jb_crearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearClienteActionPerformed
        Cliente temp = new Cliente(tf_nombreCliente.getText(),tf_edadCliente.getText());
        listaClientes.add(temp);
        tf_nombreCliente.setText("");tf_edadCliente.setText("");
    }//GEN-LAST:event_jb_crearClienteActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex()==3){
            
            DefaultComboBoxModel m1 = (DefaultComboBoxModel) cb_cajeros.getModel();
            DefaultComboBoxModel m2 = (DefaultComboBoxModel) cb_clientes.getModel();
            DefaultComboBoxModel m3 = (DefaultComboBoxModel) cb_productos.getModel();
            
            cb_cajeros.setModel(new DefaultComboBoxModel());
            cb_clientes.setModel(new DefaultComboBoxModel());
            cb_productos.setModel(new DefaultComboBoxModel());
            
            for (Cajero c : listaCajeros) {
                m1.addElement(c);
            }
            
            for (Cliente cc : listaClientes) {
                m2.addElement(cc);
            }
            
            for (Producto p : listaProductos) {
                m3.addElement(p);
            }
            
            cb_cajeros.setModel(m1);
            cb_clientes.setModel(m2);
            cb_productos.setModel(m3);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jb_crearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearOrdenActionPerformed
        Orden o = new Orden(listaCajeros.get(cb_cajeros.getSelectedIndex()-1),listaClientes.get(cb_clientes.getSelectedIndex()-1));
        o.getCajero().getListOrdenes().add(o);
        o.getCliente().setOrden(o);
        o.getCajero().getHilo().setCliente(o.getCliente()); 
        oActual = o;
        o.getCajero().getHilo().start();
    }//GEN-LAST:event_jb_crearOrdenActionPerformed

    private void jb_agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarProductoActionPerformed
        int pos = cb_clientes.getSelectedIndex()-1;
        ((Cliente)cb_clientes.getSelectedItem()).getOrden().getListaProductos().add((Producto)(cb_productos.getSelectedItem()));
        listaProductos.remove(pos);
        
        DefaultComboBoxModel m3 = new DefaultComboBoxModel();
        cb_productos.setModel(new DefaultComboBoxModel());
        for (Producto p : listaProductos) {
                m3.addElement(p);
            }
        cb_productos.setModel(m3);
    }//GEN-LAST:event_jb_agregarProductoActionPerformed

    private void jb_procesarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_procesarOrdenActionPerformed
        oActual.getCajero().getHilo().setBandera(true);
        
        
    }//GEN-LAST:event_jb_procesarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_cajeros;
    private javax.swing.JComboBox<String> cb_clientes;
    private javax.swing.JComboBox<String> cb_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_agregarProducto;
    private javax.swing.JButton jb_crearCajero;
    private javax.swing.JButton jb_crearCliente;
    private javax.swing.JButton jb_crearOrden;
    private javax.swing.JButton jb_crearProducto;
    private javax.swing.JButton jb_procesarOrden;
    private javax.swing.JTextField tf_edadCliente;
    private javax.swing.JTextField tf_idCajero;
    private javax.swing.JTextField tf_nombreCajero;
    private javax.swing.JTextField tf_nombreCliente;
    private javax.swing.JTextField tf_nombreProducto;
    private javax.swing.JTextField tf_precioProducto;
    private javax.swing.JTextField tf_tiempoProcesamiento;
    // End of variables declaration//GEN-END:variables
    Orden oActual;
}
